shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*

overrides:
  chokidar: ^5.0.0
  semver: ^7.7.4
catalog:
  '@antfu/eslint-config': ^7.7.3
  '@iconify-json/svg-spinners': ^1.2.4
  '@iconify-json/tabler': ^1.2.33
  '@iconify/utils': ^3.1.0
  '@tsconfig/node22': ^22.0.5
  '@turf/turf': ^7.3.4
  '@types/geojson': ^7946.0.16
  '@types/jsdom': ^28.0.1
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-container': ^4.0.0
  '@types/node': ^25.5.0
  '@unocss/eslint-plugin': ^66.6.7
  '@unocss/reset': ^66.6.7
  '@vitejs/plugin-vue': ^6.0.5
  '@vitest/coverage-v8': ^4.1.2
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^14.2.1
  '@vueuse/shared': ^14.2.1
  bumpp: ^10.4.1
  cesium: ^1.140.0
  cypress: ^15.13.0
  eslint: ^10.1.0
  eslint-plugin-format: ^2.0.1
  fast-glob: ^3.3.3
  gray-matter: ^4.0.3
  husky: ^9.1.7
  jsdom: ^28.1.0
  lightningcss: ^1.32.0
  lint-staged: ^16.4.0
  local-pkg: ^1.1.2
  magic-string: ^0.30.21
  markdown-it: ^14.1.1
  markdown-it-container: ^4.0.0
  pinia: ^3.0.4
  pnpm: ^10.33.0
  sass: ^1.98.0
  start-server-and-test: ^2.1.5
  stylelint: ^17.6.0
  stylelint-config-recess-order: ^7.7.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^40.0.0
  stylelint-config-standard-scss: ^17.0.0
  svgo: ^4.0.1
  taze: ^19.11.0
  tsdown: ^0.20.3
  tsx: ^4.21.0
  typescript: ^5.9.3
  unocss: ^66.6.7
  unplugin-auto-import: ^21.0.0
  unplugin-cesium: ^3.1.0
  unplugin-icons: ^23.0.1
  unplugin-vue: ^7.1.1
  unplugin-vue-components: ^31.1.0
  vite: ^7.3.1
  vite-plugin-vue-devtools: ^8.1.1
  vitepress: ^2.0.0-alpha.17
  vitest: ^4.1.2
  vue: ^3.5.31
  vue-router: ^5.0.4
  vue-tsc: ^3.2.6
  zod: ^4.3.6
