packages:
  - packages/*

catalogs:
  deps:
    '@turf/turf': ^7.2.0
    '@types/geojson': ^7946.0.16
    '@unocss/reset': ^66.3.3
    '@vueuse/core': ^13.5.0
    '@vueuse/shared': ^13.5.0
    cesium: ^1.131.0
    pinia: ^3.0.3
    vue: ^3.5.17
    vue-router: ^4.5.1
