minimumReleaseAgeExclude:
  - '@vitejs/plugin-vue@6.0.8'
  - pinia@4.0.1
shellEmulator: true

trustPolicy: no-downgrade

allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true

packages:
  - packages/*

overrides:
  chokidar: ^5.0.0
  semver: ^7.8.5
catalog:
  '@antfu/eslint-config': ^9.3.0
  '@iconify-json/svg-spinners': ^1.2.4
  '@iconify-json/tabler': ^1.2.38
  '@iconify/utils': ^3.1.4
  '@tsconfig/node22': ^22.0.5
  '@turf/turf': ^7.4.0
  '@types/geojson': ^7946.0.16
  '@types/jsdom': ^30.0.0
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-container': ^4.0.0
  '@types/node': ^26.2.0
  '@unocss/eslint-plugin': ^66.7.5
  '@vitejs/plugin-vue': ^6.0.8
  '@vitest/coverage-v8': ^4.1.10
  '@vue/test-utils': ^2.4.11
  '@vue/tsconfig': ^0.9.1
  '@vueuse/core': ^14.4.0
  '@vueuse/shared': ^14.4.0
  bumpp: ^12.2.0
  cesium: ^1.144.0
  cypress: ^15.20.0
  eslint: ^10.8.1
  eslint-plugin-format: ^2.0.1
  fast-glob: ^3.3.3
  gray-matter: ^4.0.3
  husky: ^9.1.7
  jsdom: ^30.0.1
  lightningcss: ^1.33.0
  lint-staged: ^17.3.0
  local-pkg: ^1.2.1
  magic-string: ^1.1.1
  markdown-it: ^15.0.0
  markdown-it-container: ^4.0.0
  pinia: ^4.0.2
  sass: ^1.102.0
  start-server-and-test: ^3.0.12
  svgo: ^4.0.2
  taze: ^20.0.1
  tsdown: ^0.22.14
  tsx: ^4.23.12
  typescript: ^6.0.3
  unocss: ^66.7.5
  unplugin-auto-import: ^21.1.0
  unplugin-cesium: ^3.1.0
  unplugin-icons: ^23.0.1
  unplugin-vue: ^7.2.0
  unplugin-vue-components: ^32.1.0
  vite: ^8.2.1
  vite-plugin-vue-devtools: ^8.2.1
  vitepress: ^2.0.0-alpha.19
  vitepress-plugin-llmstxt: ^0.5.2
  vitest: ^4.1.10
  vue: ^3.5.41
  vue-router: ^5.2.0
  vue-tsc: ^3.3.9
  zod: ^4.4.3
