packages:
  - packages/*

catalogs:
  deps:
    '@turf/turf': ^7.2.0
    '@types/geojson': ^7946.0.16
    '@unocss/reset': ^66.5.0
    '@vueuse/core': ^13.8.0
    '@vueuse/shared': ^13.8.0
    cesium: ^1.132.0
    pinia: ^3.0.3
    vue: ^3.5.20
    vue-router: ^4.5.1
    zod: ^4.1.5
