shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*

overrides:
  chokidar: ^5.0.0
catalog:
  '@antfu/eslint-config': ^6.7.3
  '@iconify-json/svg-spinners': ^1.2.4
  '@iconify-json/tabler': ^1.2.26
  '@iconify/utils': ^3.1.0
  '@tsconfig/node22': ^22.0.5
  '@turf/turf': ^7.3.1
  '@types/geojson': ^7946.0.16
  '@types/jsdom': ^27.0.0
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-container': ^2.0.11
  '@types/node': ^25.0.3
  '@unocss/eslint-plugin': ^66.5.12
  '@unocss/reset': ^66.5.12
  '@vitejs/plugin-vue': ^6.0.3
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^14.1.0
  '@vueuse/shared': ^14.1.0
  bumpp: ^10.3.2
  cesium: ^1.137.0
  cypress: ^15.8.2
  eslint: ^9.39.2
  eslint-plugin-format: ^1.2.0
  fast-glob: ^3.3.3
  gray-matter: ^4.0.3
  jsdom: ^27.4.0
  lightningcss: ^1.30.2
  local-pkg: ^1.1.2
  magic-string: ^0.30.21
  markdown-it: ^14.1.0
  markdown-it-container: ^4.0.0
  pinia: ^3.0.4
  pnpm: ^10.27.0
  sass: ^1.97.2
  start-server-and-test: ^2.1.3
  stylelint: ^16.26.1
  stylelint-config-recess-order: ^7.4.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^39.0.1
  svgo: ^4.0.0
  taze: ^19.9.2
  tsdown: ^0.18.4
  tsx: ^4.21.0
  typescript: ^5.9.3
  unocss: ^66.5.12
  unplugin-auto-import: ^20.3.0
  unplugin-cesium: ^3.1.0
  unplugin-icons: ^22.5.0
  unplugin-vue: ^7.1.0
  unplugin-vue-components: ^30.0.0
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-vue-devtools: ^8.0.5
  vitepress: ^2.0.0-alpha.15
  vitest: ^4.0.16
  vue: ^3.5.26
  vue-router: ^4.6.4
  vue-tsc: ^3.2.2
  zod: ^4.3.5
