packages:
  - packages/*

catalogs:
  deps:
    '@turf/turf': ^7.2.0
    '@types/geojson': ^7946.0.16
    '@unocss/reset': ^66.5.3
    '@vueuse/core': ^13.9.0
    '@vueuse/shared': ^13.9.0
    cesium: ^1.134.1
    pinia: ^3.0.3
    vue: ^3.5.22
    vue-router: ^4.5.1
    zod: ^4.1.12
