packages:
  - packages/*

catalogs:
  deps:
    '@turf/turf': ^7.3.1
    '@types/geojson': ^7946.0.16
    '@unocss/reset': ^66.5.10
    '@vueuse/core': ^14.1.0
    '@vueuse/shared': ^14.1.0
    cesium: ^1.136.0
    pinia: ^3.0.4
    vue: ^3.5.25
    vue-router: ^4.6.3
    zod: ^4.1.13
